### PR TITLE
Feature/undobar

### PR DESCRIPTION
**Pull request by alperyeg**
This PR includes the UndoBar/SnackBar with all needed files. 
The UI works fine, the last game is deleted from the database (tested on the test server), but the table is not updated. I'd like to merge this since the basic functionality is there, only the web script needs to be updated.

### CODE REVIEW

**Comment by alperyeg** [comment]
Any ideas how to update the elo ranking and table with the web script, although the last game is deleted!?

**Comment by philipp-w** [comment]
We could, similar to the current game, save the last game in a global variable in the webservice. By doing so, we would have access to the id, the involved players, the outcome and the points of the game. This is all we need to re set the elo and delete the last game.

But actually, I don't like the idea, because this does not scale to multiple games running at the same time. I think we should save the id of the last game in the app and do the rest on the webservice.

**Comment by jakobj** [comment]
as documented in #73, we plan to assign a hashtag to every game, in order to identify it uniquely. when entering a game the app has to remember that hashtag for a short while, and if requested, sends this hash to the delete game function. i think this would correspond to what you mean by game id?!

**Comment by jakobj** [comment]
i am not entirely sure i understand what's happening with the elo. if its always calculated all the way from the beginning of the time series, how can it be wrong after deleting a game? or are we already storing an elo for each player? i will anyway merge this pull request, and we can figure out the details of the elo situation in parallel to #40.

**Pull request merged**
